export type TsConfigJson = {
  extends?: string;
  compilerOptions?: {
    outDir?: string;
    types?: string[];
    module?: string;
    strict?: boolean;
    target?: string;
    moduleResolution?: string;
    esModuleInterop?: boolean;
    allowSyntheticDefaultImports?: boolean;
    forceConsistentCasingInFileNames?: boolean;
    skipLibCheck?: boolean;
    declaration?: boolean;
    declarationMap?: boolean;
    sourceMap?: boolean;
    removeComments?: boolean;
    noEmit?: boolean;
    incremental?: boolean;
    tsBuildInfoFile?: string;
    jsx?: string;
    lib?: string[];
    baseUrl?: string;
    paths?: Record<string, string[]>;
    rootDir?: string;
    composite?: boolean;
    isolatedModules?: boolean;
    allowJs?: boolean;
    checkJs?: boolean;
    maxNodeModuleJsDepth?: number;
    noImplicitAny?: boolean;
    strictNullChecks?: boolean;
    strictFunctionTypes?: boolean;
    noImplicitReturns?: boolean;
    noFallthroughCasesInSwitch?: boolean;
    noUncheckedIndexedAccess?: boolean;
    noImplicitOverride?: boolean;
    allowUnusedLabels?: boolean;
    allowUnreachableCode?: boolean;
    exactOptionalPropertyTypes?: boolean;
    noImplicitThis?: boolean;
    useUnknownInCatchVariables?: boolean;
    alwaysStrict?: boolean;
    noUnusedLocals?: boolean;
    noUnusedParameters?: boolean;
    noImplicitUseStrict?: boolean;
    noPropertyAccessFromIndexSignature?: boolean;
    noUncheckedSideEffectImports?: boolean;
  };
  include?: string[];
  exclude?: string[];
  references?: Array<{ path: string }>;
  files?: string[];
};
