import { describe, expect, it } from 'vitest';
import { unifyBundlerStats } from './unify.rsbuild.js';
import type { RsbuildCoreStats } from './unify.rsbuild.js';

describe('unifyBundlerStats', () => {
  it('should transform realistic rsbuild stats with multiple assets, chunks, and complex module dependencies', () => {
    const rsbuildStats: RsbuildCoreStats = {
      name: 'web',
      hash: 'f7f35d6bcb429212',
      version: '5.75.0',
      rspackVersion: '1.4.6',
      time: 18,
      builtAt: 1_752_462_348_764,
      publicPath: '/',
      outputPath: '/dist/rsbuild',
      assetsByChunkName: {
        index: ['static/js/index.js'],
      },
      assets: [
        {
          type: 'asset',
          name: 'static/js/async/vendors-node_modules_minimatch_dist_esm_index_js.js',
          size: 79_545,
          emitted: true,
          cached: false,
          chunkNames: [],
          chunkIdHints: ['vendors'],
          chunks: ['vendors-node_modules_minimatch_dist_esm_index_js'],
          auxiliaryChunks: [],
        },
        {
          type: 'asset',
          name: 'static/js/index.js',
          size: 38_142,
          emitted: true,
          cached: false,
          chunkNames: ['index'],
          chunkIdHints: [],
          chunks: ['index'],
          auxiliaryChunks: [],
        },
        {
          type: 'asset',
          name: 'static/js/async/src_lib_feature-2_ts.js',
          size: 708,
          emitted: true,
          cached: false,
          chunkNames: [],
          chunkIdHints: [],
          chunks: ['src_lib_feature-2_ts'],
          auxiliaryChunks: [],
        },
        {
          type: 'asset',
          name: 'index.html',
          size: 242,
          emitted: true,
          cached: false,
          chunkNames: [],
          chunkIdHints: [],
          chunks: [],
          auxiliaryChunks: [],
        },
      ],
      chunks: [
        {
          type: 'chunk',
          rendered: true,
          initial: true,
          entry: true,
          size: 1384,
          sizes: {
            javascript: 1384,
            runtime: 32_421,
          },
          names: ['index'],
          idHints: [],
          runtime: ['index'],
          files: ['static/js/index.js'],
          auxiliaryFiles: ['static/js/index.js.map'],
          hash: '9529fef35c1c4eed',
          childrenByOrder: {},
          id: 'index',
          siblings: [],
          parents: [],
          children: [
            'src_lib_feature-2_ts',
            'vendors-node_modules_minimatch_dist_esm_index_js',
          ],
          modules: [
            {
              type: 'module',
              moduleType: 'javascript/auto',
              size: 461,
              sizes: {
                javascript: 461,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              name: './src/index.ts',
              nameForCondition: '/src/index.ts',
              index: 0,
              preOrderIndex: 0,
              index2: 3,
              postOrderIndex: 3,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: false,
              failed: false,
              errors: 0,
              warnings: 0,
              id: './src/index.ts',
              chunks: ['index'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier: null,
                  module: null,
                  moduleName: null,
                  type: 'entry',
                  userRequest: './src/index.ts',
                  loc: 'index',
                  active: true,
                  moduleId: null,
                  resolvedModuleId: null,
                },
              ],
              usedExports: null,
              providedExports: ['default', 'indexOnlyFunction'],
              optimizationBailout: [],
              depth: 0,
            },
            {
              type: 'module',
              moduleType: 'javascript/auto',
              size: 376,
              sizes: {
                javascript: 376,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/feature-1.ts',
              name: './src/lib/feature-1.ts',
              nameForCondition: '/src/lib/feature-1.ts',
              index: 1,
              preOrderIndex: 1,
              index2: 1,
              postOrderIndex: 1,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: true,
              issuer:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              issuerName: './src/index.ts',
              failed: false,
              errors: 0,
              warnings: 0,
              id: './src/lib/feature-1.ts',
              issuerId: './src/index.ts',
              chunks: ['index'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
                  module: './src/index.ts',
                  moduleName: './src/index.ts',
                  type: 'esm import',
                  userRequest: './lib/feature-1',
                  loc: '1:0-51',
                  active: true,
                  moduleId: './src/index.ts',
                  resolvedModuleId: './src/index.ts',
                },
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
                  module: './src/index.ts',
                  moduleName: './src/index.ts',
                  type: 'esm import specifier',
                  userRequest: './lib/feature-1',
                  loc: '6:79-95',
                  active: true,
                  moduleId: './src/index.ts',
                  resolvedModuleId: './src/index.ts',
                },
              ],
              usedExports: null,
              providedExports: ['default', 'externalFunction'],
              optimizationBailout: [],
              depth: 1,
            },
            {
              type: 'module',
              moduleType: 'javascript/auto',
              size: 172,
              sizes: {
                javascript: 172,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/utils/math.ts',
              name: './src/lib/utils/math.ts',
              nameForCondition: '/src/lib/utils/math.ts',
              index: 3,
              preOrderIndex: 3,
              index2: 2,
              postOrderIndex: 2,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: true,
              issuer:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              issuerName: './src/index.ts',
              failed: false,
              errors: 0,
              warnings: 0,
              id: './src/lib/utils/math.ts',
              issuerId: './src/index.ts',
              chunks: ['index'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
                  module: './src/index.ts',
                  moduleName: './src/index.ts',
                  type: 'esm import',
                  userRequest: './lib/utils/math',
                  loc: '2:0-45',
                  active: true,
                  moduleId: './src/index.ts',
                  resolvedModuleId: './src/index.ts',
                },
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
                  module: './src/index.ts',
                  moduleName: './src/index.ts',
                  type: 'esm import specifier',
                  userRequest: './lib/utils/math',
                  loc: '6:30-39',
                  active: true,
                  moduleId: './src/index.ts',
                  resolvedModuleId: './src/index.ts',
                },
              ],
              usedExports: null,
              providedExports: ['add', 'calculate', 'multiply'],
              optimizationBailout: [],
              depth: 1,
            },
          ],
          origins: [
            {
              module: '',
              moduleIdentifier: '',
              moduleName: '',
              loc: 'index',
              request: './src/index.ts',
              moduleId: 'index',
            },
          ],
        },
        {
          type: 'chunk',
          rendered: true,
          initial: false,
          entry: false,
          size: 147,
          sizes: {
            javascript: 147,
          },
          names: [],
          idHints: [],
          runtime: ['index'],
          files: ['static/js/async/src_lib_feature-2_ts.js'],
          auxiliaryFiles: ['static/js/async/src_lib_feature-2_ts.js.map'],
          hash: '30813a925289ba1f',
          childrenByOrder: {},
          id: 'src_lib_feature-2_ts',
          siblings: ['vendors-node_modules_minimatch_dist_esm_index_js'],
          parents: ['index'],
          children: [],
          modules: [
            {
              type: 'module',
              moduleType: 'javascript/auto',
              size: 147,
              sizes: {
                javascript: 147,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/feature-2.ts',
              name: './src/lib/feature-2.ts',
              nameForCondition: '/src/lib/feature-2.ts',
              index: 4,
              preOrderIndex: 4,
              index2: 12,
              postOrderIndex: 12,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: false,
              issuer:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              issuerName: './src/index.ts',
              failed: false,
              errors: 0,
              warnings: 0,
              id: './src/lib/feature-2.ts',
              issuerId: './src/index.ts',
              chunks: ['src_lib_feature-2_ts'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
                  module: './src/index.ts',
                  moduleName: './src/index.ts',
                  type: 'import()',
                  userRequest: './lib/feature-2',
                  loc: '4:28-53',
                  active: true,
                  moduleId: './src/index.ts',
                  resolvedModuleId: './src/index.ts',
                },
              ],
              usedExports: null,
              providedExports: ['chart'],
              optimizationBailout: [],
              depth: 1,
            },
          ],
          origins: [
            {
              module:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              moduleIdentifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              moduleName: './src/index.ts',
              loc: '4:28-53',
              request: './lib/feature-2',
              moduleId: './src/index.ts',
            },
          ],
        },
        {
          type: 'chunk',
          rendered: true,
          initial: false,
          entry: false,
          reason: 'split chunk (cache group: defaultVendors)',
          size: 75_559,
          sizes: {
            javascript: 75_559,
          },
          names: [],
          idHints: ['vendors'],
          runtime: ['index'],
          files: [
            'static/js/async/vendors-node_modules_minimatch_dist_esm_index_js.js',
          ],
          auxiliaryFiles: [
            'static/js/async/vendors-node_modules_minimatch_dist_esm_index_js.js.map',
          ],
          hash: '204484fe4072555f',
          childrenByOrder: {},
          id: 'vendors-node_modules_minimatch_dist_esm_index_js',
          siblings: ['src_lib_feature-2_ts'],
          parents: ['index'],
          children: [],
          modules: [
            {
              type: 'module',
              moduleType: 'javascript/esm',
              size: 39_098,
              sizes: {
                javascript: 39_098,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'javascript/esm|/node_modules/minimatch/dist/esm/index.js',
              name: '../../../../../node_modules/minimatch/dist/esm/index.js',
              nameForCondition: '/node_modules/minimatch/dist/esm/index.js',
              index: 5,
              preOrderIndex: 5,
              index2: 11,
              postOrderIndex: 11,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: false,
              issuer:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/feature-2.ts',
              issuerName: './src/lib/feature-2.ts',
              failed: false,
              errors: 0,
              warnings: 0,
              id: '../../../../../node_modules/minimatch/dist/esm/index.js',
              issuerId: './src/lib/feature-2.ts',
              chunks: ['vendors-node_modules_minimatch_dist_esm_index_js'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/feature-2.ts',
                  module: './src/lib/feature-2.ts',
                  moduleName: './src/lib/feature-2.ts',
                  type: 'esm import',
                  userRequest: 'minimatch',
                  loc: '1:0-38',
                  active: true,
                  moduleId: './src/lib/feature-2.ts',
                  resolvedModuleId: './src/lib/feature-2.ts',
                },
                {
                  moduleIdentifier:
                    'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/lib/feature-2.ts',
                  module: './src/lib/feature-2.ts',
                  moduleName: './src/lib/feature-2.ts',
                  type: 'esm import specifier',
                  userRequest: 'minimatch',
                  loc: '3:11-20',
                  active: true,
                  moduleId: './src/lib/feature-2.ts',
                  resolvedModuleId: './src/lib/feature-2.ts',
                },
              ],
              usedExports: null,
              providedExports: [
                'AST',
                'GLOBSTAR',
                'Minimatch',
                'braceExpand',
                'defaults',
                'escape',
                'filter',
                'makeRe',
                'match',
                'minimatch',
                'sep',
                'unescape',
              ],
              optimizationBailout: [],
              depth: 2,
            },
          ],
          origins: [
            {
              module:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              moduleIdentifier:
                'builtin:swc-loader??ruleSet[1].rules[4].use[0]!/src/index.ts',
              moduleName: './src/index.ts',
              loc: '4:28-53',
              request: './lib/feature-2',
              moduleId: './src/index.ts',
            },
          ],
        },
      ],
      modules: [],
      entrypoints: {
        index: {
          name: 'index',
          chunks: ['index'],
          assets: [{ name: 'static/js/index.js', size: 38_142 }],
          filteredAssets: 0,
          assetsSize: 38_142,
          auxiliaryAssets: [{ name: 'static/js/index.js.map', size: 45_982 }],
          auxiliaryAssetsSize: 45_982,
          children: {},
          childAssets: {},
          isOverSizeLimit: false,
        },
      },
      namedChunkGroups: {
        index: {
          name: 'index',
          chunks: ['index'],
          assets: [{ name: 'static/js/index.js', size: 38_142 }],
          filteredAssets: 0,
          assetsSize: 38_142,
          auxiliaryAssets: [{ name: 'static/js/index.js.map', size: 45_982 }],
          auxiliaryAssetsSize: 45_982,
          children: {},
          childAssets: {},
          isOverSizeLimit: false,
        },
      },
      errors: [],
      errorsCount: 0,
      warnings: [],
      warningsCount: 0,
      children: [],
    };

    const result = unifyBundlerStats(rsbuildStats);

    expect(result).toEqual({
      'static/js/index.js': {
        path: 'static/js/index.js',
        bytes: 38_142,
        imports: [
          {
            path: './lib/feature-1',
            kind: 'import-statement',
            original: './lib/feature-1',
          },
          {
            path: './lib/utils/math',
            kind: 'import-statement',
            original: './lib/utils/math',
          },
        ],
        inputs: {
          './src/index.ts': {
            bytes: 461,
          },
          './src/lib/feature-1.ts': {
            bytes: 376,
          },
          './src/lib/utils/math.ts': {
            bytes: 172,
          },
        },
        entryPoint: './src/index.ts',
      },
      'static/js/async/src_lib_feature-2_ts.js': {
        path: 'static/js/async/src_lib_feature-2_ts.js',
        bytes: 708,
        imports: [
          {
            path: './lib/feature-2',
            kind: 'dynamic-import',
            original: './lib/feature-2',
          },
        ],
        inputs: {
          './src/lib/feature-2.ts': {
            bytes: 147,
          },
        },
      },
      'static/js/async/vendors-node_modules_minimatch_dist_esm_index_js.js': {
        path: 'static/js/async/vendors-node_modules_minimatch_dist_esm_index_js.js',
        bytes: 79_545,
        imports: [
          {
            path: 'minimatch',
            kind: 'import-statement',
            original: 'minimatch',
          },
        ],
        inputs: {
          '../../../../../node_modules/minimatch/dist/esm/index.js': {
            bytes: 39_098,
          },
        },
      },
    });
  });
});
