🧩 cli:
  - changed-files:
      - any-glob-to-any-file: 'packages/cli/src/**'

🧩 core:
  - changed-files:
      - any-glob-to-any-file: 'packages/core/src/**'

🧩 models:
  - changed-files:
      - any-glob-to-any-file: 'packages/models/src/**'

🧩 nx-plugin:
  - changed-files:
      - any-glob-to-any-file: 'packages/nx-plugin/src/**'

🧩 eslint-plugin:
  - changed-files:
      - any-glob-to-any-file: 'packages/plugin-eslint/src/**'

🧩 lighthouse-plugin:
  - changed-files:
      - any-glob-to-any-file: 'packages/plugin-lighthouse/src/**'

🧩 coverage-plugin:
  - changed-files:
      - any-glob-to-any-file: 'packages/plugin-coverage/src/**'

🧩 js-packages-plugin:
  - changed-files:
      - any-glob-to-any-file: 'packages/plugin-js-packages/src/**'

🧩 utils:
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/src/**'

🔬 testing:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/mocks/**'
          - e2e/**
          - testing/**
          - '**/vite.config*.ts'
          - 'vitest.workspace.ts'

🦾 CI/CD:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

📖 Project documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      # FIXME: this labels everything instead of just ignoring .md snapshots
      # - all-globs-to-all-files: '!**/__snapshots__/**'

🛠️ tooling:
  - changed-files:
      - any-glob-to-any-file:
          - 'tools/**'
          - '**/tsconfig*.json'
          - '**/project.json'
          - '**/package*.json'
          - '**/*eslintrc*'
          - 'nx.json'
          - '.nvmrc'
          - '.prettierrc'
          - 'esbuild.config.js'
          - '.github/ISSUE_TEMPLATE/**'
          - '.husky/**'
          - 'commitlint.config.ts'
          - '.verdaccio/config.yml'
