name: Code PushUp
description: Minimalist GitHub Action that executes Code PushUp using local @code-pushup/ci source code

inputs:
  token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}
  mode:
    description: Is `standalone` or `monorepo` mode?
    required: true

runs:
  using: composite
  steps:
    - name: Run Node script
      run: npx tsx .github/actions/code-pushup/src/runner.ts
      shell: bash
      env:
        TSX_TSCONFIG_PATH: ${{ github.workspace }}/.github/actions/code-pushup/tsconfig.json
        GH_TOKEN: ${{ inputs.token }}
        MODE: ${{ inputs.mode }}
