name: Code PushUp
description: Minimalist GitHub Action that executes Code PushUp using local @code-pushup/ci source code

inputs:
  token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: .github/actions/code-pushup
    - name: Run Node script
      run: npx tsx --tsconfig .github/actions/code-pushup/tsconfig.json .github/actions/code-pushup/src/runner.ts
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
