export const PROFILER_ENABLED_ENV_VAR = 'CP_PROFILING';
export const PROFILER_DEBUG_ENV_VAR = 'CP_PROFILER_DEBUG';
export const PROFILER_COORDINATOR_FLAG_ENV_VAR = 'CP_PROFILER_COORDINATOR';
export const PROFILER_ORIGIN_PID_ENV_VAR = 'CP_PROFILER_ORIGIN_PID';
export const PROFILER_DIRECTORY_ENV_VAR = 'CP_PROFILER_DIR';
export const PROFILER_BASE_NAME = 'trace';
export const PROFILER_DIRECTORY = './tmp/profiles';
