name: PR Title Commitlint Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Check commit messages
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
